### ISSUE TITLE
Make function for recalibrating LVDTs.

### ISSUE THREAD

**Issue by terrencetec** [gw-vis/vishack#16]
Per VIS meeting http://gwwiki.icrr.u-tokyo.ac.jp/JGWwiki/KAGRA/Subgroups/VIS/VISMinutes20201016, it is necessary to recalibrate the LVDTs after changing the LVDT cards. Assuming that the actuation efficiency stays the same, onsite recalibration by calipers is not necessary and it is certainly not possible for some suspensions and DoFs. Instead, we can simply match the new transfer function with the old one. VISHack is the perfect candidate for this job if we want to do this systematically with consistency, especially since we will have many reference transfer functions for doing system health checks. The idea is to use an optimizer to minimize some sort of error (mean square error, whitened mean square error, logarithmic mean square, ...etc) between the new transfer function and the reference transfer functions. The result is a calibration factor, so the function goes as `recalibrate_lvdt(path_to_diaggui: string, methods: list of strings) -> float`. Something like that. We can even make it a method inside the `vishack.HealthCheck` class? In this case, the health check class should be initiated with a configuration pointing to a list of LVDT related transfer function diaggui XML files. The end command-line interface would be something like `vishack -c config.ini --calibrate`

@naibafomsare what do you think? Do you have any comments?

**Comment by naibafomsare** [comment]
It's a very good idea to use VISHack for this. Here are some comments:

Very likely the actuation efficiency is not going to remain constant. The stiffness and equilibrium position of the IP or GAS filter changes with temperature. Temperature control in KAGRA is difficult and there must be a way to deal with this. Maybe the following ideas are useful:

- Create a database of setpoints and DC actuation values required to bring the GAS filter or IP to the setpoint as a function of temperature. 

- Whenever required, set the suspension in neutral state, apply the appropriate amount of DC actuation according to temperature and, finally, begin the procedure of calculating the correction factor.

- For IPs, the individual LVDT transfer functions are likely required. 

- Even if this method can be used, the new LVDT card should be prepared in a suitable way before using this method.

**Comment by terrencetec** [comment]
Seems like this is not an easy task and it goes way out of the scope of  VISHack. I will put this idea on halt.
